// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0AWtTbTUkscay0TTAbEpB6KGnxbnpVE',
    appId: '1:401057637820:web:968614117c55504fd037b9',
    messagingSenderId: '401057637820',
    projectId: 'counsellingapp-b3d27',
    authDomain: 'counsellingapp-b3d27.firebaseapp.com',
    storageBucket: 'counsellingapp-b3d27.appspot.com',
    measurementId: 'G-82SRQG0DH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-0Tpof1YcViun7FlRU6wEgojxyXV9V4',
    appId: '1:401057637820:android:23300e298082548fd037b9',
    messagingSenderId: '401057637820',
    projectId: 'counsellingapp-b3d27',
    storageBucket: 'counsellingapp-b3d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZBOPJwU3pVEdB6IgEEe8UlqjejaxJ4Q',
    appId: '1:401057637820:ios:e1cf7f1dd6d3a2add037b9',
    messagingSenderId: '401057637820',
    projectId: 'counsellingapp-b3d27',
    storageBucket: 'counsellingapp-b3d27.appspot.com',
    iosBundleId: 'com.example.counsellingappknust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZBOPJwU3pVEdB6IgEEe8UlqjejaxJ4Q',
    appId: '1:401057637820:ios:7f1613f5c2eeb9ddd037b9',
    messagingSenderId: '401057637820',
    projectId: 'counsellingapp-b3d27',
    storageBucket: 'counsellingapp-b3d27.appspot.com',
    iosBundleId: 'com.example.counsellingapp.RunnerTests',
  );
}
